<template>
  <section id="loadingComponent" class="flexRow justify-content-center fade-in">
    <span class="loader"></span>
  </section>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
@Options({})
export default class loadingComponent extends Vue {}
</script>
<style scoped>
section#loadingComponent {
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  position: absolute;
  background-color: rgba(0, 0, 0, 0.507);
  z-index: 999999;
  padding: 10%;
  cursor: progress;
}
.loader {
  width: 10vw;
  height: 10vw;
  border-radius: 50%;
  display: inline-block;
  position: relative;
  border: 3px solid;
  border-color: #fff #fff transparent;
  box-shadow: 0 0 0.4vw white;
  box-sizing: border-box;
  animation: rotation 1s linear infinite;
}
.loader::after {
  content: "";
  box-sizing: border-box;
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  margin: auto;
  border: 3px solid;
  border-color: transparent var(--corAmarelo) var(--corAmarelo);

  width: 5vw;
  height: 5vw;
  border-radius: 50%;
  animation: rotationBack 0.5s linear infinite;
  transform-origin: center center;
}
.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

/* ---------------------------------------------- * Generated by Animista on
2023-5-29 10:26:46 * Licensed under FreeBSD License. * See
http://animista.net/license for more info. * w: http://animista.net, t:
@cssanimista * ---------------------------------------------- */ /** *
---------------------------------------- * animation fade-in *
---------------------------------------- */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@media (max-width: 1500px) {
  .loader {
    width: 100px;
    height: 100px;
  }
  .loader::after {
    width: 50px;
    height: 50px;
  }
}
@keyframes rotation {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

@keyframes rotationBack {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(-360deg);
  }
}
</style>
